"""Unit tests for multi-node failover and multi-harness cascade in RemoteMultiHarnessModelProvider."""

from __future__ import annotations

import json
from unittest.mock import MagicMock, patch

import pytest

from core.execution.providers import RemoteMultiHarnessModelProvider, get_model_provider


def test_multi_node_failover_desktop_down_notebook_success() -> None:
    """Simulates primary Desktop offline and verifies automatic transparent failover to Notebook."""
    provider = RemoteMultiHarnessModelProvider(
        node_urls=["http://100.78.181.90:8080", "http://100.81.84.124:8080"],
        default_harness="codex",
    )

    def fake_urlopen(req, timeout=None):
        url = req.full_url if hasattr(req, "full_url") else str(req)
        # Desktop health probe fails
        if "100.78.181.90" in url and "/health" in url:
            raise ConnectionError("Host unreachable")
        # Notebook health probe succeeds
        if "100.81.84.124" in url and "/health" in url:
            mock_resp = MagicMock()
            mock_resp.status = 200
            mock_resp.__enter__.return_value = mock_resp
            return mock_resp
        # Notebook execution endpoint succeeds
        if "100.81.84.124" in url and "/harness/execute" in url:
            mock_resp = MagicMock()
            mock_resp.read.return_value = json.dumps({
                "success": True,
                "text": "def test_failover(): pass",
                "model": "gpt-5.6-sol",
                "node_id": "ai-notebook",
            }).encode("utf-8")
            mock_resp.__enter__.return_value = mock_resp
            return mock_resp
        raise ValueError(f"Unexpected URL in test: {url}")

    with patch("urllib.request.urlopen", side_effect=fake_urlopen):
        res = provider.generate("Generate failover test", model="codex")

    assert res.text == "def test_failover(): pass"
    assert res.measured_cost == 0.0
    assert res.metadata["remote_url"] == "http://100.81.84.124:8080"
    assert res.metadata["backend"] == "remote_codex"


def test_multi_harness_cascade_grok_exhausted_codex_succeeds() -> None:
    """Simulates Grok returning quota exhausted (402/error) and verifies cascade to Codex."""
    provider = RemoteMultiHarnessModelProvider(
        node_urls=["http://100.81.84.124:8080"],
    )

    def fake_urlopen(req, timeout=None):
        url = req.full_url if hasattr(req, "full_url") else str(req)
        if "/health" in url:
            mock_resp = MagicMock()
            mock_resp.status = 200
            mock_resp.__enter__.return_value = mock_resp
            return mock_resp

        if "/harness/execute" in url:
            body = json.loads(req.data.decode("utf-8"))
            harness = body.get("harness")
            if harness == "grok":
                # Simulate Grok usage balance exhausted
                mock_resp = MagicMock()
                mock_resp.read.return_value = json.dumps({
                    "success": False,
                    "harness": "grok",
                    "error": "API error (status 402 Payment Required): Grok Build usage balance exhausted",
                }).encode("utf-8")
                mock_resp.__enter__.return_value = mock_resp
                return mock_resp
            elif harness == "codex":
                mock_resp = MagicMock()
                mock_resp.read.return_value = json.dumps({
                    "success": True,
                    "harness": "codex",
                    "text": "Generated by fallback Codex",
                    "model": "gpt-5.6-sol",
                }).encode("utf-8")
                mock_resp.__enter__.return_value = mock_resp
                return mock_resp
        raise ValueError(f"Unexpected request: {url}")

    with patch("urllib.request.urlopen", side_effect=fake_urlopen):
        res = provider.generate(
            "Implement feature",
            candidate_harnesses=["grok", "codex"],
        )

    assert res.text == "Generated by fallback Codex"
    assert res.metadata["harness"] == "codex"
    assert res.measured_cost == 0.0


def test_structured_harness_failure_fails_over_to_next_node() -> None:
    """A structured failure on Desktop must retry the same harness on Notebook."""
    provider = RemoteMultiHarnessModelProvider(
        node_urls=["http://100.78.181.90:8080", "http://100.81.84.124:8080"],
    )

    def fake_urlopen(req, timeout=None):
        url = req.full_url if hasattr(req, "full_url") else str(req)
        if "/health" in url:
            response = MagicMock()
            response.status = 200
            response.__enter__.return_value = response
            return response

        if "/harness/execute" in url and "100.78.181.90" in url:
            response = MagicMock()
            response.read.return_value = json.dumps({
                "success": False,
                "harness": "claude",
                "error": "Claude Code executable not installed on this host",
            }).encode("utf-8")
            response.__enter__.return_value = response
            return response

        if "/harness/execute" in url and "100.81.84.124" in url:
            response = MagicMock()
            response.read.return_value = json.dumps({
                "success": True,
                "harness": "claude",
                "text": "Notebook Claude response",
                "model": "claude-sonnet",
                "node_id": "ai-notebook",
            }).encode("utf-8")
            response.__enter__.return_value = response
            return response

        raise ValueError(f"Unexpected URL in test: {url}")

    with patch("urllib.request.urlopen", side_effect=fake_urlopen):
        result = provider.generate(
            "Run Claude headless probe",
            candidate_harnesses=["claude"],
        )

    assert result.text == "Notebook Claude response"
    assert result.metadata["harness"] == "claude"
    assert result.metadata["remote_url"] == "http://100.81.84.124:8080"


def test_all_nodes_offline_raises_clean_error() -> None:
    """Verifies that if all nodes are offline, RuntimeError is raised with diagnostic context."""
    provider = RemoteMultiHarnessModelProvider(
        node_urls=["http://desktop:8080", "http://notebook:8080"],
        default_harness="codex",
    )

    with patch("urllib.request.urlopen", side_effect=ConnectionError("Unreachable")):
        with pytest.raises(RuntimeError, match="Remote harness execution failed across all nodes"):
            provider.generate("Test failure")


def test_factory_registration_and_aliases() -> None:
    """get_model_provider returns RemoteMultiHarnessModelProvider for all aliases."""
    for alias in ("remote_harness", "codex", "remote_codex", "grok", "remote_grok", "antigravity", "remote_antigravity"):
        p = get_model_provider(alias, node_urls=["http://test:8080"])
        assert isinstance(p, RemoteMultiHarnessModelProvider)
