"""Build artifacts, byte hashing and immutable build recipes.

Governed by HF-12-01, HF-12-02 and CONTRACTS.md.
Provides reproducible byte hashing, fail-closed metadata checks,
and idempotent artifact promotion without redundant rebuilding.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import subprocess
import threading
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LEDGER_PATH = PROJECT_ROOT / ".factory" / "artifacts" / "build_ledger.json"


class BuildError(Exception):
    """Base exception for build and artifact failures."""


class BuildHashMismatchError(BuildError):
    """Raised when generated bytes do not match expected metadata digest."""


class BuildExecutionError(BuildError):
    """Raised when an underlying build command fails."""


class Claim(BaseModel):
    """Lease claim model compliant with CONTRACTS.md."""

    model_config = ConfigDict(extra="ignore")

    job_key: Optional[Any] = None
    lease_id: str = ""
    owner: str = ""
    fencing_token: int = 1
    expires_at: Optional[datetime] = None
    reservation_id: Optional[str] = None
    route_ref: Optional[str] = None


class BuildRecipe(BaseModel):
    """Specification of build inputs and target environment."""

    model_config = ConfigDict(extra="ignore")

    project_id: str = Field(description="Unique project identifier (e.g. darkfac, site-ggcampos, segundo-cerebro, jarvis)")
    target: str = Field(description="Target platform/packaging (e.g. dokploy_docker_compose, static_web, local_service)")
    build_cmd: Optional[str] = Field(default=None, description="Command to execute for compilation/build")
    dist_path: Optional[str] = Field(default=None, description="Path to build distribution artifacts directory or file")
    dockerfile: Optional[str] = Field(default=None, description="Path to Dockerfile if containerized")
    env_vars: Dict[str, str] = Field(default_factory=dict, description="Environment variables passed during build")
    expected_byte_digest: Optional[str] = Field(default=None, description="Expected SHA-256 digest of output bytes for fail-closed validation")


class ArtifactRef(BaseModel):
    """Immutable reference to a verified build artifact with cryptographic digest."""

    model_config = ConfigDict(extra="ignore", frozen=True)

    artifact_id: str = Field(description="Deterministic artifact identifier")
    source_sha: str = Field(description="Source Git commit SHA")
    byte_digest: str = Field(description="Cryptographic SHA-256 hash of generated bytes")
    byte_size: int = Field(ge=0, description="Size in bytes of generated artifact")
    oci_digest: Optional[str] = Field(default=None, description="OCI image digest (e.g. sha256:...) if container")
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC), description="Creation timestamp in UTC")
    verified: bool = Field(default=True, description="Whether byte digest has been cryptographically verified")


def compute_bytes_digest(data: bytes) -> str:
    """Computes standard hexadecimal SHA-256 digest of bytes."""
    return hashlib.sha256(data).hexdigest()


def compute_path_bytes(path: Path) -> tuple[bytes, str, int]:
    """Reads a file or directory tree and returns (canonical_bytes, sha256, total_size)."""
    if not path.exists():
        raise FileNotFoundError(f"Path does not exist: {path}")

    if path.is_file():
        content = path.read_bytes()
        return content, hashlib.sha256(content).hexdigest(), len(content)

    # Directory: canonical tree bytes
    buffer = bytearray()
    total_size = 0
    for file_path in sorted(path.rglob("*")):
        if file_path.is_file():
            rel_path = file_path.relative_to(path).as_posix().encode("utf-8")
            file_bytes = file_path.read_bytes()
            total_size += len(file_bytes)
            buffer.extend(rel_path)
            buffer.extend(b"\x00")
            buffer.extend(file_bytes)
            buffer.extend(b"\x00")

    raw_bytes = bytes(buffer)
    return raw_bytes, hashlib.sha256(raw_bytes).hexdigest(), total_size


class BuildService:
    """Build engine managing compilation, byte integrity, and artifact promotion."""

    def __init__(self, ledger_path: Optional[Path] = None) -> None:
        self.ledger_path = Path(ledger_path).resolve() if ledger_path else None
        self._lock = threading.Lock()
        self._ledger: Dict[str, ArtifactRef] = {}  # artifact_id -> ArtifactRef
        self._by_source_target: Dict[str, str] = {}  # f"{project_id}:{target}:{source_sha}" -> artifact_id

        if self.ledger_path and self.ledger_path.exists():
            self._load_ledger()

    def _load_ledger(self) -> None:
        if not self.ledger_path or not self.ledger_path.exists():
            return
        try:
            data = json.loads(self.ledger_path.read_text(encoding="utf-8"))
            for item in data.get("artifacts", []):
                ref = ArtifactRef.model_validate(item)
                self._ledger[ref.artifact_id] = ref
            for key, art_id in data.get("index", {}).items():
                self._by_source_target[key] = art_id
        except Exception as exc:
            logger.warning("Could not load build ledger from %s: %s", self.ledger_path, exc)

    def _save_ledger(self) -> None:
        if not self.ledger_path:
            return
        self.ledger_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "schema_version": "1.0",
            "artifacts": [ref.model_dump(mode="json") for ref in self._ledger.values()],
            "index": self._by_source_target,
        }
        self.ledger_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    def build(
        self,
        source_sha: str,
        recipe: BuildRecipe,
        claim: Optional[Union[Claim, Any]] = None,
        *,
        simulated_bytes: Optional[bytes] = None,
        expected_byte_digest: Optional[str] = None,
        oci_digest: Optional[str] = None,
    ) -> ArtifactRef:
        """Executes or simulates compilation, verifying bytes integrity and enabling promotion."""
        if not source_sha or not source_sha.strip():
            raise ValueError("source_sha must be non-empty")

        index_key = f"{recipe.project_id}:{recipe.target}:{source_sha}"

        # 1. Promoção sem rebuild: se os bytes e o source_sha já existem no ledger de artefatos
        with self._lock:
            existing_art_id = self._by_source_target.get(index_key)
            if existing_art_id and existing_art_id in self._ledger:
                existing_ref = self._ledger[existing_art_id]
                # If expected_byte_digest is supplied, verify it matches
                target_expected = expected_byte_digest or recipe.expected_byte_digest
                if target_expected and existing_ref.byte_digest != target_expected:
                    raise BuildHashMismatchError(
                        f"Hash mismatch for existing artifact: metadata claimed {target_expected}, "
                        f"but ledger artifact has {existing_ref.byte_digest}"
                    )
                logger.info(
                    "Promoting existing artifact %s for %s (%s) without rebuild",
                    existing_ref.artifact_id,
                    recipe.project_id,
                    source_sha[:8],
                )
                return existing_ref

        # 2. Executa ou simula compilação real e captura os bytes gerados
        generated_bytes: bytes
        computed_digest: str
        byte_size: int

        if simulated_bytes is not None:
            generated_bytes = simulated_bytes
            computed_digest = compute_bytes_digest(generated_bytes)
            byte_size = len(generated_bytes)
        elif recipe.dist_path:
            dist = Path(recipe.dist_path)
            if recipe.build_cmd and not dist.exists():
                env = os.environ.copy()
                env.update(recipe.env_vars)
                res = subprocess.run(
                    recipe.build_cmd,
                    shell=True,
                    capture_output=True,
                    text=False,
                    env=env,
                )
                if res.returncode != 0:
                    raise BuildExecutionError(
                        f"Build command failed with code {res.returncode}: {res.stderr.decode(errors='replace')}"
                    )

            if not dist.exists():
                raise FileNotFoundError(f"dist_path not found after build: {recipe.dist_path}")

            generated_bytes, computed_digest, byte_size = compute_path_bytes(dist)
        elif recipe.build_cmd:
            env = os.environ.copy()
            env.update(recipe.env_vars)
            res = subprocess.run(
                recipe.build_cmd,
                shell=True,
                capture_output=True,
                text=False,
                env=env,
            )
            if res.returncode != 0:
                raise BuildExecutionError(
                    f"Build command failed with code {res.returncode}: {res.stderr.decode(errors='replace')}"
                )
            generated_bytes = res.stdout
            computed_digest = compute_bytes_digest(generated_bytes)
            byte_size = len(generated_bytes)
        else:
            # Default deterministic bytes for the recipe and source_sha
            generated_bytes = f"artifact:{recipe.project_id}:{recipe.target}:{source_sha}".encode("utf-8")
            computed_digest = compute_bytes_digest(generated_bytes)
            byte_size = len(generated_bytes)

        # 3. Fail-closed: se o SHA de metadados for igual mas os bytes gerados forem diferentes, rejeita sumariamente
        effective_expected = expected_byte_digest or recipe.expected_byte_digest
        if effective_expected is not None and effective_expected != computed_digest:
            raise BuildHashMismatchError(
                f"Fail-closed hash mismatch: metadata declared {effective_expected}, "
                f"but generated bytes produced {computed_digest}"
            )

        # 4. Criação do ArtifactRef imutável
        artifact_id = f"art_{hashlib.sha256(f'{recipe.project_id}:{recipe.target}:{source_sha}:{computed_digest}'.encode()).hexdigest()[:16]}"
        effective_oci = oci_digest
        if effective_oci is None and recipe.target == "dokploy_docker_compose":
            effective_oci = f"sha256:{computed_digest}"

        artifact_ref = ArtifactRef(
            artifact_id=artifact_id,
            source_sha=source_sha,
            byte_digest=computed_digest,
            byte_size=byte_size,
            oci_digest=effective_oci,
            created_at=datetime.now(UTC),
            verified=True,
        )

        with self._lock:
            self._ledger[artifact_ref.artifact_id] = artifact_ref
            self._by_source_target[index_key] = artifact_ref.artifact_id
            self._save_ledger()

        return artifact_ref

    def get_artifact(self, artifact_id: str) -> Optional[ArtifactRef]:
        with self._lock:
            return self._ledger.get(artifact_id)

    def list_artifacts(self, project_id: Optional[str] = None) -> List[ArtifactRef]:
        with self._lock:
            if not project_id:
                return list(self._ledger.values())
            prefix = f"{project_id}:"
            matching_ids = {art_id for key, art_id in self._by_source_target.items() if key.startswith(prefix)}
            return [self._ledger[aid] for aid in matching_ids if aid in self._ledger]


__all__ = [
    "ArtifactRef",
    "BuildError",
    "BuildExecutionError",
    "BuildHashMismatchError",
    "BuildRecipe",
    "BuildService",
    "Claim",
    "compute_bytes_digest",
    "compute_path_bytes",
]
